
databases:
  - name: factory_operation_db
    plan: free
    databaseName: factory_operation_db
    user: factory_operation_user

services:
  - type: web
    plan: free
    name: factory_operation # ドメインの先頭に指定したいフレーズ
    runtime: python
    buildCommand: "./build.sh"
    startCommand: 'gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --workers 2'

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: factory_operation_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEBUG  # この行を追加
        value: "False"  # 本番環境では通常Falseに設定